### PR TITLE
Update SkillData.lua

### PR DESCRIPTION
**Pull request by Svertalf**
RU translation
Some string sorting (EN/DE/FR/RU)

### CODE REVIEW

**Comment by wduda** [comment]
While vastly better (only 600 lines to review instead of 3700), this PR still has many unexpected changes to formatting and English strings. Until the PR is updated to only touch RU strings and nothing else I will not be accepting it into the main TW II branch.

**Comment by whiterabbit963** [comment]
@Svertalf please note that you can preview the combined changes for a file in this PR by clicking on the "File Changed" tab at the top. Because this is such a large file, you will need to click the "load the diff" text for the SkillData.lua file.

**Comment by Svertalf** [comment]
I will be out of the access zone in the near future. An urgent business trip. I almost reworked file.

**Comment by wduda** [comment]
If you away @Svertalf I will likely try and merge some of your changes, and revert the unwanted ones. But that is time I would prefer to spend on developing TW II further rather than removing whitespace.

**Pull request merged**
