### PR TITLE
Multiple features by whiterabbit (#172)

### PR DESCRIPTION
**Pull request by wduda**
* add enable/disable all buttons

* add enable/disable overlapping skills buttons #171

* remove unnecessary args in MapWindow

* improve nil handling of location coordinate map

* update mapwindow after changing enable state

* optimize mass enable/disable update performance

* refactor TravelDictionary

Move all logic out of language files.
Replace global location variables with a single global: TravelInfo. Update TravelDictionary counts on every AddSkill(). Minor simplification to TravelShortcut ctor.
Refactored several places where code was duplicated. Removed broken and unnecessary handling of skills being removed from game.

* replace LC ints with turbine named constants

* add feature to ignore escape to close the main window #100

---------

### CODE REVIEW

**Comment by whiterabbit963** [comment]
Assuming the merge window for v1.5.0 is still open, I was going to try to push an update for #101 later tonight after I finish testing it.

**Comment by wduda** [comment]
I was aware. Other plugins use helper plugins to load significant amounts of data. MoorMap for example has helper plugins you never load yourself, the loading is triggered from MoorMap code to utilize the initial loading, and the helper plugin is then unloaded right away as well.

I also found a bug with the pulldown list in your miniUI, on my Mariner the skills would not change at all whenever a new skill was selected from the pulldown. Had no time to look into that.

**Comment by wduda** [comment]
I need to check, maybe something went wrong with the version I merged together.

**Comment by whiterabbit963** [comment]
I have a patch for the empty pulldown issue I noticed. I may roll it in with the #101 global settings change and create a single PR.
Let me know what you find with the pulldown on your side.

**Comment by wduda** [comment]
@whiterabbit963 I am encountering one bug:
- when the option to travel on pulldown selection is checked in options, and the skill is selected from the pulldown, it does not automatically travel as it should (that option turned on saves a click when using pulldown)

**Comment by wduda** [comment]
Otherwise the Mini UI is a great addition, as are the global settings.

**Comment by whiterabbit963** [comment]
> @whiterabbit963 I am encountering one bug:
> 
> * when the option to travel on pulldown selection is checked in options, and the skill is selected from the pulldown, it does not automatically travel as it should (that option turned on saves a click when using pulldown)

Good catch, will investigate.

**Comment by wduda** [comment]
@whiterabbit963 thanks for all the fixes. I will test a bit today, try to make a description of the new features for users and hopefully release later today.

**Comment by wduda** [comment]
Come what may, I am pushing this out today. I'd rather do bugfix releases after then wait longer.

**Comment by whiterabbit963** [comment]
Found this `loadGlobalDefaultsString = "Charger par défaut globales"";`
I could push a pr, but it might be faster if you just get it.

**Comment by wduda** [comment]
I'll fix that. I might also change some German text since I am also a German native speaker.

**Comment by wduda** [comment]
Well, release will have to be tomorrow. I decided I cannot post this without at least some new screenshots. Tomorrow or Tuesday it is, I have one of these two evenings free,

**Comment by whiterabbit963** [comment]
> I'll fix that. I might also change some German text since I am also a German native speaker.

Thanks! The online translators are never any good and I never got very far in either French or German.

**Pull request merged**
