### PR TITLE
Update SkillData.lua

### PR DESCRIPTION
**Pull request by Svertalf**
RU translation
Some string sorting
Code  standartization

### CODE REVIEW

**Comment by wduda** [comment]
@Svertalf - I cannot accept your "code standardization" changes because these only make a file with 3700 lines of code even longer without adding any readability like regular code would need. Please change the PR to only include string changes without the formatting.

**Comment by whiterabbit963** [comment]
I also see some changes to the EN locale that I believe are inaccurate. For example, the skill "Guide to the War-stead" had the vendor name "Quartermaster (Riders of Rohan)" and the vendor name was changed to the "Rohirrim Quartermaster". I have yet to verify in-game, but according to the lotro-wiki, the "Rohirrim Quartermaster" refers to a lvl 60 barterer. The skill in question is from Far Anorien which is a lvl 105 region.
Before making any changes to the EN locale, please verify the change is accurate and include them in separate commits.

**Comment by Svertalf** [comment]
> @Svertalf - I cannot accept your "code standardization" changes because these only make a file with 3700 lines of code even longer without adding any readability like regular code would need. Please change the PR to only include string changes without the formatting.

There are two variants:
EN={vendor="Quartermaster (Helmingas)", }  or EN={vendor="Quartermaster (Helmingas)"},
What's right?

**Comment by Svertalf** [comment]
> I also see some changes to the EN locale that I believe are inaccurate. For example, the skill "Guide to the War-stead" had the vendor name "Quartermaster (Riders of Rohan)" and the vendor name was changed to the "Rohirrim Quartermaster". I have yet to verify in-game, but according to the lotro-wiki, the "Rohirrim Quartermaster" refers to a lvl 65-75 barterer. The skill in question is from Far Anorien which is a lvl 100-105 region. Before making any changes to the EN locale, please verify the changes are accurate and include them in separate commits.

It was an old version of the file. I was distracted and saved the wrong version.

**Comment by Svertalf** [comment]
I'm new at GitHub. So don't know what PR mean.

**Comment by wduda** [comment]
> > @Svertalf - I cannot accept your "code standardization" changes because these only make a file with 3700 lines of code even longer without adding any readability like regular code would need. Please change the PR to only include string changes without the formatting.
> 
> There are two variants: EN={vendor="Quartermaster (Helmingas)", } or EN={vendor="Quartermaster (Helmingas)"}, What's right?
> 
> I suggest to remove the extra comma+space. If so I'll make another commit without extra formatting.

@Svertalf I would suggest you pause any attempts at changing any formatting whatsoever. They are well intended but they cause a huge waste of time. Any line where you changed just a comma is marked as changed. Now I do not know if you changed the comma correctly, maybe made a mistake, maybe changed the English text into the French one, it can be anything. So I would have to read every change dline anch check it manually.

As an experiment, go to https://github.com/wduda/TravelWindowII/pull/216/files and check on the far right. It will say +1,878 −1,890 as in 1878 lines added and 1890 lines deleted, so either I have to trust your changes blindly or I have to read 3700+ lines of changes to verify them.

Meanwhile the formatting changes are not adding any, absolutely any value. The code works before and after the same and is readable enough.

I will be harsh but I would rather not accept any improved locale strings than blindly trust 3700 lines of changes.

As @whiterabbit963 says, please either change this PR or submit a new pull request that has only string changes, no formatting changes, and if you want to help with the EN/DE/FR strings let's add these in a separate changeset and PR.

**Comment by wduda** [comment]
> I'm new at GitHub. So don't know what PR mean.

Ah. I did not see that answer. PR stands for pull request. GitHub is a website that helps in the use of GIT, so software version control tool. I can highly recommend finding a beginners tutorial to learn that a bit, for example https://dev.to/saloman_james/a-comprehensive-guide-to-version-control-with-git-and-github-3m0n, but I am sure such tutorials also exist in Russian if that is your native language.

**Comment by Svertalf** [comment]
Close this PR. I made new.

**Pull request closed without merging**
