### PR TITLE
Added Mariner Skills and River Hobbit racial

### PR DESCRIPTION
**Pull request by mhdubose**
Missing translations of the skill names, but here's PR to add the Mariner sailing skills.
Also added some missing skills to the map windows to fix the index

### CODE REVIEW

**Comment by Dromo** [comment]
Thanks, was going to do it also but found this one, here are translations 
> ID,English,French,Deutsch
> 0x70066100,Sail to Celondim,Naviguer vers Celondim,Segelt nach Celondim
> 0x70066101,Sail to the Brown Lands,Naviguer vers les Terres brunes,Segelt in die Braunen Lande
> 0x70066105,Sail to Trader's Wharf,Naviguer vers le Quai des marchands,Segelt zum Händlerkai
> 0x70066109,Sail to after-battle Osgiliath,Naviguer vers Osgiliath après la bataille,Segelt ins schlachtgezeichnete Osgiliath
> 0x7006610C,Sail to Lake-town,Cap sur la Ville du Lac,Segelt nach Seestadt.
> 0x7006610E,Sail to the Mirk-eaves,Naviguer vers l'Orée Noire,Segelt zur Dunkelsenke
> 0x7006610F,Sail to Tinnudir,Naviguer vers Tinnudir,Segelt nach Tinnudir
> 0x70066117,Sail to Dol Amroth,Naviguer vers Dol Amroth,Segelt nach Dol Amroth
> 0x7006611A,Sail to Buckland,Naviguer vers le Pays de Bouc,Segelt nach Bockland
> 0x7006611B,Sail to Pelargir,Naviguer vers Pelargir,Segelt nach Pelargir
> 0x7006611C,Sail to Sûri-kylä,Naviguer vers Sûri-kylä,Segelt nach Sûri-kylä
> 0x7006611E,Sail to Lothlórien,Naviguer vers la Lothlorien,Segelt nach Lothlórien
> 0x70066120,Sail to Tharbad,Naviguer vers le Gué de Sarn,Segelt zur Sarnfurt
> 0x70066121,Sail to Snowbourn,Naviguer vers Neigebronne,Segelt nach Schneegrenze
> 0x70066D31,Return to Lyndelby,Retour à Lyndelby,Kehrt zu Lyndelby zurück.

**Comment by mhdubose** [comment]
Thanks @Dromo. I added those translations, so it all should be good to go now. Would be great to have this merged @wduda

**Comment by wduda** [comment]
Wierd. I have not received an email about this PR until now when you tagged me. Need to check my GitHub notification settings.

I will try and get this code merged tomorrow, I would like to clean up the settings for the maps a bit or it will break that feature completely.

**Comment by wduda** [comment]
Accepting the merge as is, will make the necessary changes in branches on my side.

**Pull request merged**
