### PR TITLE
Performance fixes

### PR DESCRIPTION
**Pull request by wduda**

### CODE REVIEW

**Comment by whiterabbit963** [comment]
I significantly rebased and simplified my git branch of performance improvements. Since it is a rebase, I moved it to performance_updates. It is on top off of my fix_dictionary branch/fix. Let me know if this works better for you and I can make a new pull request.

**Comment by wduda** [comment]
This is great, I will try and merge this in first before we tackle map window updates, potentially release together with some further duplication fixes.

**Comment by whiterabbit963** [comment]
Alright, I synced performance remote with the performance_updates remote. This branch includes the fixes from the Grid Resizing PR (#144). Hopefully, this makes the process easier for you.

**Comment by whiterabbit963** [comment]
@wduda It seems github doesn't like it when the remote branch is deleted and readded. I probably should have done a force push instead. In any case, in order to try to alleviate any confusion, I will try to explain. The performance and performance_updates remotes both point to the same place. They are rebased directly on top of the fix_dictionary branch and can be merged cleanly with the integration remote. They include all of the grid_resizing and other performance/ui updates I have made. They do not include the map window updates. I will save those for another PR, once the performance updates are merged.

Hopefully that makes sense. Sorry for any confusion as I cleaned/rebased my git commits to make them easier to digest for merging.

**Pull request merged**
